### ISSUE TITLE
Make week1.txt more readable

### ISSUE THREAD

**Issue by sohamparate** [sohamp19/DSA-Weekly#1]
1. Add direct links to texts
2. Add bullet points

**Comment by Ali-Nasrolahi** [comment]
you may use markdown (.md) or html.
I prefer markdown so here's a link to pretty straight-forward tutorial. 
[Markdown tutorial](https://www.markdowntutorial.com/) 
specificity for your issue in markdown. I would use
```
- item1
- item2
- item3
 - nested item
 [Google](www.google.com) for web links
and [Header in same file](exact name with lower-case and dash for spaces)
```
For example:
```
[Item One](#item-one)
## Item One
 goofy texts
## item two
## item three
```

**Comment by sohamparate** [comment]
@Ali-Nasrolahi 

Thanks for the great tutorial!  
Just completed it in one go.

**Comment by Ali-Nasrolahi** [comment]
I'm glad it was helpful.
